#!/bin/sh

db_root_password="Sup3rS3kur3P4ssw0rd"

secure_mysql=$(expect -c "

set timeout 10
spawn mysql_secure_installation

expect \"Enter current password for root:\"
send \"$MYSQL\r\"

expect \"Would you like to setup VALIDATE PASSWORD plugin?\"
send \"n\r\"

expect \"Change the password for root ?\"
send \"n\r\"

expect \"Remove anonymous users?\"
send \"y\r\"

expect \"Disallow root login remotely?\"
send \"n\r\"

expect \"Remove test database and access to it?\"
send \"y\r\"

expect \"Reload privilege tables now?\"
send \"y\r\"

expect eof
")

echo "$secure_mysql"
